server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
spring:
  application:
    name: customer
  datasource:
      name: test
      url: jdbc:mysql://localhost:3306/mytest
      username: root
      password: 12345678
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  #  password: 12345
    #连接超时 ms
    timeout: 200
    pool:
      max-active: 200
      #连接池中的最小空闲连接，默认值为0
      min-idle: 0
      #连接池中的最大空闲连接，默认值为8
      max-idle: 8
      max-wait: -1
mybatis:
#  mapper-locations: classpath*:com/dec/dao/*.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dec.entity
#  config-locations: classpath:mybatis/mybatis-config.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql